export const HANDLE_SELECTION = 'HANDLE_SELECTION';
export const SET_INGREDIENTS = 'SET_INGREDIENTS';
export const CLEAR_INGREDIENTS = 'CLEAR_INGREDIENTS';
export const FETCH_INGREDIENTS_FAILED = 'FETCH_INGREDIENTS_FAILED';
